-- MEMBER
INSERT INTO MEMBER (MID, MPW, MNAME, MTEL, MEMAIL, MGENDER, MBIRTH, MADDRESS)
    VALUES ('test1', '111', '사용자1' , '010-1111-1111', 'test1@gmail.com', 'M', 
            '1995/01/01', '서울시 용산구');
            
INSERT INTO MEMBER (MID, MPW, MNAME, MTEL, MEMAIL, MGENDER, MBIRTH, MADDRESS)
    VALUES ('test2', '111', '사용자2' , '010-2222-2222', 'test2@gmail.com', 'M', 
            '1995/01/01', '서울시 용산구');
            
-- SHELTER
INSERT INTO SHELTER(SID, SPW, SNAME, STEL, SEMAIL, SADDRESS)
    VALUES ('SHELTER1', '111', '서울유기동물보호소', '02-111-1111', 'seoul@animal.co.kr', '서울시 용산구');

INSERT INTO SHELTER(SID, SPW, SNAME, STEL, SEMAIL, SADDRESS)
    VALUES ('SHELTER2', '111', '파주유기동물보호소', '031-222-2222', 'paju@animal.co.kr', '경기도 파주시');
    
-- ANIMAL
INSERT INTO ANIMAL(ANO, SID, APHOTO, ABREED, AGENDER, AAGE, AWEIGHT, ACONTENT, AADDRESS, ARDATE, AADOPT, AIP)
    VALUES (ANIMAL_ANO_SEQ.NEXTVAL, 'SHELTER1', 'NOIMG.jpg', '진돗개', '수컷(중성화 O)', '1', '10',
            '사람을 잘 따라요', '서울시 용산역 부근', SYSDATE, 'PROTECT', '197.0.0.1');
            
INSERT INTO ANIMAL(ANO, SID, APHOTO, ABREED, AGENDER, 
                   AAGE, AWEIGHT, ACONTENT, AADDRESS, ARDATE, AADOPT, AIP)
    VALUES (ANIMAL_ANO_SEQ.NEXTVAL, 'SHELTER2', 'NOIMG.jpg', '푸들', '암컷(중성화 O)', '5', '4',
            '사람을 잘 따라요', '중산마을 9단지', SYSDATE, 'PROTECT', '197.0.0.1');

INSERT INTO ANIMAL(ANO, SID, APHOTO, ABREED, AGENDER, 
                   AAGE, AWEIGHT, ACONTENT, AADDRESS, AADOPT, AIP)
    VALUES (ANIMAL_ANO_SEQ.NEXTVAL, 'SHELTER2', 'NOIMG.jpg', '푸들', '암컷(중성화 O)', '5', '4',
            '사람을 잘 따라요', '중산마을 9단지', 'PROTECT', '197.0.0.1');

-- ANIMALCOMMENT
INSERT INTO ANIMALCOMMENT (ACNO, MID, ANO, ACCONTENT, ACRDATE, ACIP)
    VALUES (ANIMALCOMMENT_ACNO_SEQ.NEXTVAL, 'test1', '2', '좋은 주인 만나렴', SYSDATE, '210.0.0.1');

SELECT * FROM ANIMALCOMMENT;
-- REVIEWBOARD
INSERT INTO REVIEWBOARD
    (RNO, MID, SID, RTITLE, RCONTENT, RPW, RPHOTO, RRDATE, RHIT, RGROUP, RSTEP, RINDENT, RIP)
VALUES (REVIEWBOARD_RNO_SEQ.NEXTVAL, 'test1', NULL, '입양 5주차 후기', '입양 5주차 이제는 친해졌어요',
        '111', NULL, SYSDATE, 0, REVIEWBOARD_RNO_SEQ.CURRVAL, 0, 0, '197.0.0.1');
        
INSERT INTO REVIEWBOARD
    (RNO, MID, SID, RTITLE, RCONTENT, RPW, RPHOTO, RRDATE, RHIT, RGROUP, RSTEP, RINDENT, RIP)
VALUES (REVIEWBOARD_RNO_SEQ.NEXTVAL, 'test1', NULL, '입양 6주차 후기', '입양 6주차 산책도 잘해요',
        '111', NULL, SYSDATE, 0, REVIEWBOARD_RNO_SEQ.CURRVAL, 0, 0, '197.0.0.1');
        
INSERT INTO REVIEWBOARD
    (RNO, MID, SID, RTITLE, RCONTENT, RPW, RPHOTO, RRDATE, RHIT, RGROUP, RSTEP, RINDENT, RIP)
VALUES (REVIEWBOARD_RNO_SEQ.NEXTVAL, NULL, 'SHELTER1', '입양 6주차 후기', '입양 6주차 산책도 잘해요',
        '111', NULL, SYSDATE, 0, REVIEWBOARD_RNO_SEQ.CURRVAL, 0, 0, '197.0.0.1');
        
-- LIKElIST
INSERT INTO LIKELIST (LNO, MID, ANO)
    VALUES (LIKELIST_LNO_SEQ.NEXTVAL ,'test1', '2');
    
    INSERT INTO LIKELIST (LNO, MID, ANO)
    VALUES (LIKELIST_LNO_SEQ.NEXTVAL ,'test1', '3');

SELECT * FROM MEMBER;
SELECT * FROM SHELTER;
SELECT * FROM ANIMAL;
SELECT * FROM ANIMALCOMMENT;
SELECT * FROM REVIEWBOARD;
SELECT * FROM LIKELIST;

COMMIT;